// this contains all Dialogues, they are used in itemInfo.js

const allDialogues = [
    "I need something to water this plant.",
    "Great. But it's empty. What now?",
    "The water isn't running...",
    "I turned the valve. The water should be running now.",
    "Finally I can water the plant!",
    "Looks a little better already! Let's see what else I can do here.",
    "Oh no, these plants don't look any better",
    "Doesn't seem like water will be of much help here.",
    "Nope, that's locked.",
    "Yup, you needed that water. Oh, what's that?",
    "Lucky me. Oh, and there's some fertilizer too.",
    "Neat! This will come in handy",
    "I'd try to open the door, but I don't want to hurt the poor monstera.",
    "Yup, way better. Now it's not blocking the door anymore. I should try the fertilizer on the Calathea, too.",
    "I think I should see if I can help the calathea first.",
    "Oh yes, that definitely helped you, huh? There's dead leaves though...",
    "Seems like a little study...",
    "There's a handwritten note on the book: 'Remember: Drink enough, eat enough, get rid of what hurts you and embrace what makes you happy.'",
    "What's that? Food for... butterflies?",
    "I bet I can use these around here",
    "Another key?",
    "Aaaaand the dead leaves are gone! You look better, little calathea. But something's still missing.",
    "Can't open that, the ivy has grown over the handle.",
    "That ivy was really overgrown!",
    "Oh, so the key was for the window...",
    "I'm sure I can lure them in somehow.",
    "Come here, little butterflies.",
    "Look at you, all healthy and green again.",
    "Let's take care of the calathea first.",
]

export { allDialogues }